name: Deploy to Azure

on:
  push:
    branches:
      - master

# env:
#   AZURE_WEBAPP_NAME: "APP NAME FROM AZURE"
      
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.0.x

    - name: Build
      run: |
        dotnet build

    - name: download
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool --version 3.6.0

    - name: download
      run: |
        vc-build compress

        